/* empty css                      */import{a as f,S as p,i as c}from"./assets/vendor-D0cagnvz.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const y="49034890-15d0e202b9bb59c7b310d7a4f",h="https://pixabay.com/api/";async function d(l,o=1,s=40){try{const r=await f.get(h,{params:{key:y,q:l,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:s}});return{images:r.data.hits,total:r.data.totalHits}}catch(r){throw console.error("Ошибка при получении данных:",r),new Error("Не удалось загрузить изображения")}}const u=document.querySelector(".gallery");let L=new p(".gallery a",{captionsData:"alt",captionDelay:250});function m(l){const o=l.map(({webformatURL:s,largeImageURL:r,tags:e,likes:t,views:a,comments:i,downloads:n})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${r}">
                <img class="gallery-image" src="${s}" alt="${e}" loading="lazy" />
            </a>
            <div class="image-info">
                <p><strong>Likes:</strong> ${t}</p>
                <p><strong>Views:</strong> ${a}</p>
                <p><strong>Comments:</strong> ${i}</p>
                <p><strong>Downloads:</strong> ${n}</p>
            </div>
        </li>
    `).join("");u.insertAdjacentHTML("beforeend",o),L.refresh()}function b(){u.innerHTML=""}document.addEventListener("DOMContentLoaded",()=>{const l=document.querySelector(".form");document.querySelector(".gallery");const o=document.querySelector(".load-more"),s=document.querySelector(".loader");let r="",e=1;const t=40;let a=0;l.addEventListener("submit",async i=>{if(i.preventDefault(),r=i.currentTarget.elements.query.value.trim(),!r){c.warning({title:"Увага",message:"Введіть запит для пошуку!"});return}e=1,b(),o.classList.add("hidden"),s.classList.remove("hidden");try{const{images:n,total:g}=await d(r,e,t);if(a=g,n.length===0){c.error({title:"Помилка",message:"Нічого не знайдено!"});return}m(n),a>t&&o.classList.remove("hidden")}catch{c.error({title:"Помилка",message:"Не вдалося завантажити зображення."})}finally{s.classList.add("hidden")}}),o.addEventListener("click",async()=>{e++,s.classList.remove("hidden");try{const{images:i}=await d(r,e,t);m(i),e*t>=a&&(o.classList.add("hidden"),c.info({title:"Інформація",message:"Це останні зображення."}));const{height:n}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}catch{c.error({title:"Помилка",message:"Не вдалося завантажити зображення."})}finally{s.classList.add("hidden")}})});
//# sourceMappingURL=index.js.map
