/* empty css                      */import{a as b,S as w,i as n}from"./assets/vendor-D0cagnvz.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const v="49034890-15d0e202b9bb59c7b310d7a4f",q="https://pixabay.com/api/";async function f(o,t=1,a=40){try{const s=await b.get(q,{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:a}});return{images:s.data.hits,total:s.data.totalHits}}catch(s){throw console.error("Ошибка при получении данных:",s),new Error("Не удалось загрузить изображения")}}const p=document.querySelector(".gallery");let S=new w(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:i,comments:h,downloads:L})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${s}">
                <img class="gallery-image" src="${a}" alt="${e}" loading="lazy" />
            </a>
            <div class="image-info">
                <p><strong>Likes:</strong> ${r}</p>
                <p><strong>Views:</strong> ${i}</p>
                <p><strong>Comments:</strong> ${h}</p>
                <p><strong>Downloads:</strong> ${L}</p>
            </div>
        </li>
    `).join("");p.insertAdjacentHTML("beforeend",t),S.refresh()}function $(){p.innerHTML=""}const E=document.querySelector(".form");document.querySelector(".gallery");const d=document.querySelector(".load-more"),m=document.querySelector(".loader");let c="",l=1;const u=40;let g=0;E.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.currentTarget.elements.query.value.trim(),!c){n.warning({title:"Увага",message:"Введіть запит для пошуку!"});return}l=1,$(),d.classList.add("hidden"),m.classList.remove("hidden");try{const{images:t,total:a}=await f(c,l,u);if(g=a,t.length===0){n.error({title:"Помилка",message:"Нічого не знайдено!"});return}y(t),g>u&&d.classList.remove("hidden")}catch{n.error({title:"Помилка",message:"Не вдалося завантажити зображення."})}finally{m.classList.add("hidden")}});d.addEventListener("click",async()=>{l++,m.classList.remove("hidden");try{const{images:o}=await f(c,l,u);y(o),l*u>=g&&(d.classList.add("hidden"),n.info({title:"Інформація",message:"Це останні зображення."}));const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{n.error({title:"Помилка",message:"Не вдалося завантажити зображення."})}finally{m.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
