/* empty css                      */import{a as L,S as b}from"./assets/vendor-DTuICwlt.js";import n from"izitoast";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const w="49034890-15d0e202b9bb59c7b310d7a4f",q="https://pixabay.com/api/";async function g(o,t=1,a=40){try{const s=await L.get(q,{params:{key:w,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:a}});return{images:s.data.hits,total:s.data.totalHits}}catch(s){throw console.error("Ошибка при получении данных:",s),new Error("Не удалось загрузить изображения")}}const f=document.querySelector(".gallery");let v=new b(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const t=o.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:i,comments:y,downloads:h})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${s}">
                <img class="gallery-image" src="${a}" alt="${e}" loading="lazy" />
            </a>
            <div class="image-info">
                <p><strong>Likes:</strong> ${r}</p>
                <p><strong>Views:</strong> ${i}</p>
                <p><strong>Comments:</strong> ${y}</p>
                <p><strong>Downloads:</strong> ${h}</p>
            </div>
        </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),v.refresh()}function S(){f.innerHTML=""}const $=document.querySelector(".search-form");document.querySelector(".gallery");const d=document.querySelector(".load-more");let c="",l=1;const m=40;let u=0;$.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.currentTarget.elements.query.value.trim(),!c){n.warning({title:"Увага",message:"Введіть запит для пошуку!"});return}l=1,S(),d.classList.add("hidden");try{const{images:t,total:a}=await g(c,l,m);if(u=a,t.length===0){n.error({title:"Помилка",message:"Нічого не знайдено!"});return}p(t),u>m&&d.classList.remove("hidden")}catch{n.error({title:"Помилка",message:"Не вдалося завантажити зображення."})}});d.addEventListener("click",async()=>{l++;try{const{images:o}=await g(c,l,m);p(o),l*m>=u&&(d.classList.add("hidden"),n.info({title:"Інформація",message:"Це останні зображення."}));const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{n.error({title:"Помилка",message:"Не вдалося завантажити зображення."})}});
//# sourceMappingURL=index.js.map
